name: fetcher
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^3.3.2
  riverpod_annotation: ^4.0.3
  
  # Core Functionality
  flutter_usb: ^0.0.4
  disk_space: ^0.2.1
  file_picker: ^11.0.2
  path_provider: ^2.1.1
  permission_handler: ^12.0.3
  
  # Utils
  equatable: ^2.0.5
  freezed_annotation: ^3.1.0
  json_annotation: ^4.8.1
  synchronized: ^3.1.0
  crypto: ^3.0.3
  
  # UI
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  freezed: ^3.2.6-dev.1
  json_serializable: ^6.7.1
  riverpod_generator: ^4.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
